# Generated by Django 6.1.1 on 2026-09-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
