# Generated by Django 6.1.1 on 2026-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_pedido_taxa_entrega"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pix", "Pix"),
                    ("Cartão", "Cartão (na entrega)"),
                    ("Dinheiro", "Dinheiro (na entrega)"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
