# Generated by Django 6.0.6 on 2026-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(max_length=200),
        ),
    ]
