# Generated by Django 6.0.3 on 2026-07-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foto_alter_produto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
