# Generated by Django 6.0.7 on 2026-07-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Hamburguer', 'Hamburguer'), ('Pizza', 'Pizza'), ('Batata', 'Batata'), ('Bebida', 'Bebida'), ('Sobremesa', 'Sobremesa'), ('Salgado', 'Salgado')], default='Hamburguer', max_length=30),
            preserve_default=False,
        ),
    ]
