# Generated by Django 6.0.7 on 2026-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Hamburguer', 'Hamburguer'), ('Cachorro quente', 'Cachorro quente'), ('Pizza', 'Pizza'), ('Batata', 'Batata'), ('Bebida', 'Bebida'), ('Sobremesa', 'Sobremesa'), ('Salgado', 'Salgado')], max_length=30),
        ),
    ]
