# Generated by Django 6.1.1 on 2026-09-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(choices=[('Hamburguer', 'Hamburguer'), ('Cachorro quente', 'Cachorro quente'), ('Pizza', 'Pizza'), ('Batata', 'Batata'), ('Bebida', 'Bebida'), ('Sobremesa', 'Sobremesa'), ('Salgado', 'Salgado')], max_length=30)),
                ('imagem', models.ImageField(upload_to='produtos/')),
            ],
        ),
    ]
