# Generated by Django 6.1.1 on 2026-09-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria_nova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria'),
        ),
    ]
