# Generated by Django 6.1.1 on 2026-09-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_categoria_nova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_nova',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria'),
        ),
    ]
