# Generated by Django 6.1.2 on 2026-10-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_entregador',
            field=models.BooleanField(default=False, verbose_name='Entregador'),
        ),
    ]
